### ISSUE TITLE
3 Errors when executing yarn at installation

### ISSUE THREAD

**Issue by jjj120** [kryops/remote-mixer#3]
When executing the first `yarn` command I get the following three errors:

```
ERROR` in ./src/settings.tsx
Module build failed (from ../node_modules/@linaria/webpack-loader/lib/index.js):
<path-to-repo>\remote-mixer-main\node_modules\@linaria\babel-preset\lib\module.js:355
      throw new EvalError(`${e.message} in${callstack.join('\n| ')}\n`);
      ^
EvalError: Cannot use import statement outside a module in
| <path-to-repo>\remote-mixer-main\node_modules\polished\dist\polished.esm.js
| <path-to-repo>\remote-mixer-main\frontend\src\ui\styles.ts
| <path-to-repo>\remote-mixer-main\frontend\src\settings.tsx
```

```
ERROR in ./src/ui/global-styles.ts
Module build failed (from ../node_modules/@linaria/webpack-loader/lib/index.js):
<path-to-repo>\remote-mixer-main\node_modules\@linaria\babel-preset\lib\module.js:355
      throw new EvalError(`${e.message} in${callstack.join('\n| ')}\n`);
      ^

EvalError: Cannot use import statement outside a module in
| <path-to-repo>\remote-mixer-main\node_modules\polished\dist\polished.esm.js
| <path-to-repo>\remote-mixer-main\frontend\src\ui\styles.ts
| <path-to-repo>\remote-mixer-main\frontend\src\ui\global-styles.ts
```

```
ERROR in ./src/ui/icons/icon.tsx
Module build failed (from ../node_modules/@linaria/webpack-loader/lib/index.js):
<path-to-repo>remote-mixer-main\node_modules\@linaria\babel-preset\lib\module.js:355
      throw new EvalError(`${e.message} in${callstack.join('\n| ')}\n`);
      ^

EvalError: Cannot use import statement outside a module in
| <path-to-repo>\remote-mixer-main\node_modules\polished\dist\polished.esm.js
| <path-to-repo>\remote-mixer-main\frontend\src\ui\styles.ts
| <path-to-repo>\remote-mixer-main\frontend\src\ui\icons\icon.tsx
```

What is the problem there? What am I not doing right?

**Comment by kryops** [comment]
Hi @jjj120,

that looks strange indeed. The error seems to be something like https://github.com/callstack/linaria/issues/1207 in combination with the `polished` library, but I can't reproduce it on my machine.

Do you have the latest updates (i.e. you are on commit 02bd81f7e6fc04ced70d8ac8cc46fa6e50646694)? Did you modify any code?

One thing you could try is to change the import in `frontend/src/ui/styles.ts` from


```ts
import { mix } from 'polished'
```

to

```ts
import mix from 'polished/lib/color/mix'
```

and then execute `yarn`.

**Comment by jjj120** [comment]
Thanks, with this change it compiled now. 

I also tried the docker installation before the change and there was no problem.

**Comment by kryops** [comment]
Interesting. Thanks for verifying the fix! I just pushed https://github.com/kryops/remote-mixer/commit/e903de3948762d5dfa16338205e2cf6fa9a4aef0 with the changed import.

**Comment by kryops** [comment]
With the current version of Linaria, the fixed import does not compile anymore, so I had to revert it. However, they also fixed some issues around ESM on their end, so hopefully this fix is no longer necessary.

Please let me know if you start having issues again.
